'use client';

import React from 'react';
import Link from 'next/link';
import Navbar from '@/components/Navbar';
import Footer from '@/components/Footer';
import { ArrowRight, Building2, ShoppingBag, Utensils, Briefcase, Heart, GraduationCap } from 'lucide-react';

const samplePlans = [
  {
    id: 'tech-startup',
    title: 'Tech Startup',
    industry: 'Technology',
    description: 'A B2B SaaS company launching a project management tool for remote teams.',
    icon: Building2,
    color: 'bg-blue-50',
    iconColor: 'text-blue-600',
    hoverColor: 'hover:border-blue-300',
  },
  {
    id: 'ecommerce-fashion',
    title: 'E-commerce Fashion',
    industry: 'Retail',
    description: 'An online boutique selling sustainable and eco-friendly clothing for young professionals.',
    icon: ShoppingBag,
    color: 'bg-purple-50',
    iconColor: 'text-purple-600',
    hoverColor: 'hover:border-purple-300',
  },
  {
    id: 'local-restaurant',
    title: 'Local Restaurant',
    industry: 'Food & Beverage',
    description: 'A farm-to-table restaurant focusing on locally sourced ingredients and seasonal menus.',
    icon: Utensils,
    color: 'bg-orange-50',
    iconColor: 'text-orange-600',
    hoverColor: 'hover:border-orange-300',
  },
  {
    id: 'consulting-firm',
    title: 'Consulting Firm',
    industry: 'Professional Services',
    description: 'A management consulting firm specializing in digital transformation for mid-size companies.',
    icon: Briefcase,
    color: 'bg-gray-100',
    iconColor: 'text-gray-600',
    hoverColor: 'hover:border-gray-400',
  },
  {
    id: 'fitness-studio',
    title: 'Fitness Studio',
    industry: 'Health & Wellness',
    description: 'A boutique fitness studio offering personalized training and group classes.',
    icon: Heart,
    color: 'bg-red-50',
    iconColor: 'text-red-600',
    hoverColor: 'hover:border-red-300',
  },
  {
    id: 'online-education',
    title: 'Online Education',
    industry: 'Education',
    description: 'An e-learning platform providing professional development courses for career advancement.',
    icon: GraduationCap,
    color: 'bg-green-50',
    iconColor: 'text-green-600',
    hoverColor: 'hover:border-green-300',
  },
];

export default function SamplePlansPage() {
  return (
    <div className="min-h-screen bg-[#f0f4f8]">
      <Navbar />

      {/* Hero Section */}
      <section className="py-16 lg:py-20">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center max-w-3xl mx-auto">
            <h1 className="text-4xl lg:text-5xl font-bold text-gray-900 mb-6">
              Sample Marketing Plans
            </h1>
            <p className="text-xl text-gray-600 leading-relaxed">
              Explore real examples of marketing plans generated by our AI for different industries.
              See what your custom plan could look like.
            </p>
          </div>
        </div>
      </section>

      {/* Sample Plans Grid */}
      <section className="pb-20 lg:pb-28">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
            {samplePlans.map((plan) => {
              const IconComponent = plan.icon;
              return (
                <Link
                  key={plan.id}
                  href={`/sample-plans/${plan.id}`}
                  className={`group bg-white rounded-2xl border border-gray-200 p-8 transition-all duration-300 hover:shadow-xl hover:-translate-y-1 ${plan.hoverColor}`}
                >
                  <div className={`${plan.color} w-14 h-14 rounded-xl flex items-center justify-center mb-6`}>
                    <IconComponent className={`w-7 h-7 ${plan.iconColor}`} />
                  </div>
                  <div className="mb-2">
                    <span className="text-xs font-semibold text-gray-500 uppercase tracking-wider">
                      {plan.industry}
                    </span>
                  </div>
                  <h3 className="text-xl font-semibold text-gray-900 mb-3">
                    {plan.title}
                  </h3>
                  <p className="text-gray-600 mb-6">
                    {plan.description}
                  </p>
                  <div className="flex items-center text-[#0F5AE0] font-medium group-hover:text-[#0C48B3]">
                    View Plan
                    <ArrowRight className="ml-2 h-4 w-4 group-hover:translate-x-1 transition-transform" />
                  </div>
                </Link>
              );
            })}
          </div>

          {/* CTA Section */}
          <div className="mt-16 text-center">
            <div className="bg-white rounded-2xl border border-gray-200 p-12 max-w-2xl mx-auto">
              <h2 className="text-2xl font-bold text-gray-900 mb-4">
                Ready to Create Your Own Plan?
              </h2>
              <p className="text-gray-600 mb-8">
                Get a marketing plan tailored specifically to your business in minutes.
              </p>
              <Link href="/questionnaire">
                <button className="bg-[#0F5AE0] hover:bg-[#0C48B3] text-white px-8 py-4 text-base font-semibold rounded-lg hover:scale-105 transition-all duration-300 cursor-pointer inline-flex items-center">
                  Create Your Plan Now
                  <ArrowRight className="ml-2 h-5 w-5" />
                </button>
              </Link>
            </div>
          </div>
        </div>
      </section>

      <Footer />
    </div>
  );
}
